### ISSUE TITLE
“..\..\ThirdLibrary\portmidi\source\platform\win\pmwin.c”: No such file or directory

### ISSUE THREAD

**Issue by zhang-ray** [RemiliaMIDIMaker/MIDI-Player#5]
I got some errors like:
`“..\..\ThirdLibrary\portmidi\source\platform\win\pmwin.c”: No such file or directory` error

**Comment by ChillMagic** [comment]
> I got some errors like:
> `“..\..\ThirdLibrary\portmidi\source\platform\win\pmwin.c”: No such file or directory` error

Hello,
You can try
```
git submodule update --init
```
